### PR TITLE
Complete work of the Privacy SIG, commits rebased

### PR DESCRIPTION
**Pull request by jwfuller**

### CODE REVIEW

**Comment by craigmcnally** [comment]
When we first developed this, we made a concious decision to use the terminology "personal data" because it's scope is much broader than PII.  Please explaine the rationale behind moving to PII in this PR.

**Comment by craigmcnally** [comment]
This PR lacks a description.  Generally speaking it's a good practice to provide the following:
* Purpose - what is the PR trying to accomplish?
* Approach - description of the steps taken to accomplish the desired goal
* Additional info - includes relevant links to supporting documentation, etc.

**Comment by inkuss** [comment]
1. Remarks on the formal procedure:
I have just checked that this PR does exactly the same thing as PR#6.
The only thing different are the commit messages.
This is also what @jwfuller tells me in Slack chat, that he made less commits with larger messages. But he also corrected a typo (which I didn't see).

The only thing I miss is my commit message about introducing the different log levels :-)

I neither see a compelling reason to have all these changes in a new pull request and rewrite the commit messages, since there is already a pull request.
The usual procedure would be to comment on the existing PR (#6) that there is a typo (or whatever changes one wants to propose).
I think the main reason to have this new PR is to minimize the number of commit messages.

So, for this case, I consent to withdraw my pull request, after this new one may have been merged.

2. And now my content-related remarks:
Several PRs of Julian Ladisch have not been merged, yet. But they should also be considered.
I absolutely second Craig's and Julian's remarks that the scope of "personal data" is much broader than PII.
To be able to run a FOLIO system in compliance with GDPR we must define personal data in the way Julian describes.
This terminology might have been discussed in Privacy SIG meetings and I might have attended and raised no objection. If this is the case, I will have to explain that I can follow a discussion better in written form than oral, for some reasons.

**Comment by craigmcnally** [comment]
@inkuss I wasn't referring to the commit messages, but rather the Pull Request Description.  
image

**Comment by inkuss** [comment]
On this website, the difference between PII and personal data in the sense of GDPR is being explained: https://techgdpr.com/blog/difference-between-pii-and-personal-data/ . And, yes, it seems to be a North American vs. European definition.
In particular, Cookies and IP addresses are being considered personal data in the sense of GDPR, but no PII.

**Pull request closed without merging**
